[workspace]
resolver = "2"
members = [
    "dusk",
    "libdusk",
    "dls",
    "dusk-proc-macros",
    "xtask"
]

[profile.dev.package."*"]
opt-level = 3

[profile.profiling]
inherits = 'release'
debug = 1