[package]
name = "dusklang"
version = "0.1.5"
authors = ["Zach <zachrwolfe@me.com>"]
edition = "2021"
default-run = "dusklang"
description = "This crate contains a compiler for the Dusk programming language"
license = "MIT"
repository = "https://github.com/dusklang/dusk"
homepage = "https://dusklang.org/"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
libdusk = { version = "0.1", path = "../libdusk" }
dusk_dire = { version = "0.1", path = "../dire" }

# Should compile away to nothing when the "dvd" feature below is not enabled
dvd_ipc = { version = "0.1", path = "../dvd_ipc" }

[features]
# Enables the Dusk visual debugger
dvd = ["dvd_ipc/enabled"]
