[package]
name = "dusk"
version = "0.1.0"
authors = ["Zach <zachrwolfe@me.com>"]
edition = "2021"
default-run = "dusk"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
libdusk = { path = "../libdusk" }
dire = { path = "../dire/" }